### ISSUE TITLE
Unused class

### ISSUE THREAD

**Issue by discospiff** [sourav786/XML-Project#5]
Is this class used?  If not, it's clutter, and should be removed.

https://github.com/sourav786/XML-Project/blob/294e2e83544b0d54308c0aa924f24a29b2ec2a09/Models/CincinnatiAccident.cs#L8

**Comment by sourav786** [comment]
Hello Professor,

This class generated for showing the fellow student JSON data. I have created this class from Merged JSON

**Comment by discospiff** [comment]
Actually... it looks like this is used in the other project's JSON to consume... nevermind.
